title: "Bindu Pagad"
description: "Salesforce Developer | APEX | LWC | Javascript | REST APIs | AWS | Heroku "
baseurl: ""  # Important: blank for root site
url: "https://misspagad.github.io"

theme: jekyll-theme-cayman

plugins:
  - jekyll-feed

author:
  name: "Bindu Pagad"
  email: bindupagad181997@gmail.com
